### ISSUE TITLE
Is it possible for us to add comments to cells?

### ISSUE THREAD

**Issue by Huang-Hong** [jmcnamara/rust_xlsxwriter#79] opened 2024-01-23 06:49 UTC
### Question

Is it possible for us to add comments to cells? It seems that the relevant function can not be found
![image](https://github.com/jmcnamara/rust_xlsxwriter/assets/32867672/db0c88cb-9a84-4250-a206-09a42d71b211)

**Comment by jmcnamara** [comment] 2024-01-23 09:35
Not currently. It is a planned feature, on the Roadmap, since this feature is supported in the Python version: https://xlsxwriter.readthedocs.io/working_with_cell_comments.html

**Comment by Huang-Hong** [comment] 2024-01-23 10:08
ok，thanks

**Comment by Huang-Hong** [comment] 2024-01-23 10:09
> > Is it possible for us to add comments to cells
> 
> Not currently. It is a planned feature, on the Roadmap, since this feature is supported in the Python version: https://xlsxwriter.readthedocs.io/working_with_cell_comments.html

got it，thanks

**Comment by jmcnamara** [comment] 2024-02-03 19:55
Closing this as a duplicate of the Roadmap item for "Cell Comments" in #1

**Closed by jmcnamara** 2024-02-03 19:55 UTC
Labels: question
